id: P32DA93CD
initial_creation_type: input
source_metadata:
  title: Guru Drakpo Series
  language: en
  description: 'Texts related to Guru Drakpo (gu ru drag po), the wrathful manifestation
    of Guru Padmasambhava, in all his various forms:'
  volume:
    53571e9c81b84f289f2e8877acaa8eb6:
      title: Wrathful Guru Mantra Visualization
      parent: Mantra Visualization
    4ffde6790b0743d0b84ab5d9ef0e909a:
      title: Daily Practice of Guru Drakpo
      parent: Sādhanas
created_at: '2022-03-01T03:44:35.619697'
last_modified_at: '2022-03-01T03:44:35.619704'
